name: Echo Hi

on:
  push:  # Triggers on every push to the repository
    branches:
      - 'main'  # Listen to pushes on all branches

jobs:
  say_hi:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello
        run: echo "Helloo"

        
