name: Build-SDK

on:
  pull_request:
    types: [opened, edited]
    branches: [ main ]

jobs:
  build-sdk:
    if: github.head_ref == 'hotfix/*'
    runs-on: ubuntu-latest  
    steps:
      - run: |
            echo "The Title of your PR is ${{ github.event.pull_request.title }}"
            echo "Build SDK..."
            echo "This PR is opened by ${{ github.event.pull_request.user.login }} ."
