name: Build-SDK

on:
  pull_request:
    types: [edited]
    branches: [ main ]

jobs:
  test-pr:
    if: |
      startsWith(github.head_ref, 'hotfix/') &&
      !contains(github.event.pull_request.title,'crea')
    runs-on: ubuntu-latest
    steps:
      - run: |
            echo "The Title of your PR is ${{ github.event.pull_request.title }}"
            echo "This PR is opened by ${{ github.event.pull_request.user.login }} ."
            echo "PR Link: https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }}"
            echo "https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }}" > PR_LINK
            echo $PR_LINK
