name: Build-SDK

on:
  pull_request:
    branches: [ main ]

jobs:
  build-sdk:
    if: startsWith(github.head_ref, 'hotfix/')
    runs-on: ubuntu-latest  
    steps:
      - run: echo "Build SDK..."
